#
# TzarBot - Run All Demos
# Uruchom na VM DEV aby wykonac wszystkie demo i wygenerowac raporty
#

param(
    [string]$OutputDir = "C:\TzarBot-Demo",
    [string]$ProjectPath = "C:\TzarBot",
    [switch]$SkipScreenshots
)

$ErrorActionPreference = "Continue"
$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"

Write-Host @"

╔══════════════════════════════════════════════════════════════╗
║              TzarBot Demo Suite                              ║
║                                                              ║
║  This script will run all phase demos and generate reports  ║
╚══════════════════════════════════════════════════════════════╝

"@ -ForegroundColor Cyan

# Utworz glowny katalog
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

$scriptDir = $PSScriptRoot
$summaryFile = Join-Path $OutputDir "demo_summary_$timestamp.md"

$allResults = @()

# ========================================
# Phase 0 Demo
# ========================================
Write-Host "`n" + "="*60 -ForegroundColor Yellow
Write-Host "  PHASE 0: Prerequisites Verification" -ForegroundColor Yellow
Write-Host "="*60 -ForegroundColor Yellow

$phase0Script = Join-Path $scriptDir "Run-Phase0Demo.ps1"
if (Test-Path $phase0Script) {
    $phase0Result = & $phase0Script -OutputDir (Join-Path $OutputDir "Phase0") -SkipScreenshots:$SkipScreenshots
    $allResults += [PSCustomObject]@{
        Phase = "Phase 0"
        Name = "Prerequisites"
        Success = $phase0Result.Success
        Details = "Pass: $($phase0Result.PassCount), Fail: $($phase0Result.FailCount)"
        Report = $phase0Result.ReportFile
    }
} else {
    Write-Host "Phase 0 script not found: $phase0Script" -ForegroundColor Red
    $allResults += [PSCustomObject]@{
        Phase = "Phase 0"
        Name = "Prerequisites"
        Success = $false
        Details = "Script not found"
        Report = $null
    }
}

# ========================================
# Phase 1 Demo
# ========================================
Write-Host "`n" + "="*60 -ForegroundColor Yellow
Write-Host "  PHASE 1: Game Interface" -ForegroundColor Yellow
Write-Host "="*60 -ForegroundColor Yellow

$phase1Script = Join-Path $scriptDir "Run-Phase1Demo.ps1"
if (Test-Path $phase1Script) {
    $phase1Result = & $phase1Script -OutputDir (Join-Path $OutputDir "Phase1") -ProjectPath $ProjectPath -SkipScreenshots:$SkipScreenshots
    $allResults += [PSCustomObject]@{
        Phase = "Phase 1"
        Name = "Game Interface"
        Success = $phase1Result.Success
        Details = "Tests: $($phase1Result.PassedTests) passed, $($phase1Result.FailedTests) failed"
        Report = $phase1Result.ReportFile
    }
} else {
    Write-Host "Phase 1 script not found: $phase1Script" -ForegroundColor Red
    $allResults += [PSCustomObject]@{
        Phase = "Phase 1"
        Name = "Game Interface"
        Success = $false
        Details = "Script not found"
        Report = $null
    }
}

# ========================================
# Generate Summary Report
# ========================================
Write-Host "`n" + "="*60 -ForegroundColor Cyan
Write-Host "  Generating Summary Report" -ForegroundColor Cyan
Write-Host "="*60 -ForegroundColor Cyan

$successCount = ($allResults | Where-Object { $_.Success }).Count
$totalPhases = $allResults.Count

$summaryContent = @"
# TzarBot Demo Summary Report

**Generated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
**VM Name:** DEV
**Overall Status:** $(if ($successCount -eq $totalPhases) { "ALL PHASES PASSED" } else { "SOME PHASES FAILED" })

---

## Phase Results

| Phase | Name | Status | Details |
|-------|------|--------|---------|
$($allResults | ForEach-Object { "| $($_.Phase) | $($_.Name) | $(if ($_.Success) { 'PASS' } else { 'FAIL' }) | $($_.Details) |" } | Out-String)

---

## Individual Reports

$($allResults | ForEach-Object { "- **$($_.Phase):** $($_.Report)" } | Out-String)

---

## Output Directory Structure

``````
$OutputDir
├── Phase0/
│   ├── phase0_report_*.md
│   ├── phase0_demo_*.log
│   └── *.png (screenshots)
├── Phase1/
│   ├── phase1_report_*.md
│   ├── build_*.log
│   ├── tests_*.log
│   └── *.png (screenshots)
└── demo_summary_*.md
``````

---

## Summary

| Metric | Value |
|--------|-------|
| Phases Tested | $totalPhases |
| Phases Passed | $successCount |
| Phases Failed | $($totalPhases - $successCount) |
| Success Rate | $([math]::Round($successCount / $totalPhases * 100, 1))% |

---

## Next Steps

$(if ($successCount -eq $totalPhases) {
@"
All demos passed! You can proceed with:
1. Copy reports to host for documentation
2. Continue with Phase 2: Neural Network Architecture
"@
} else {
@"
Some demos failed. Please:
1. Review individual phase reports
2. Fix any issues
3. Re-run demos
"@
})

---

*Generated by TzarBot Demo Suite*
"@

Set-Content -Path $summaryFile -Value $summaryContent -Encoding UTF8

# ========================================
# Final Output
# ========================================
Write-Host @"

╔══════════════════════════════════════════════════════════════╗
║              Demo Suite Complete                             ║
╠══════════════════════════════════════════════════════════════╣
"@ -ForegroundColor $(if ($successCount -eq $totalPhases) { "Green" } else { "Yellow" })

foreach ($result in $allResults) {
    $status = if ($result.Success) { "[PASS]" } else { "[FAIL]" }
    $color = if ($result.Success) { "Green" } else { "Red" }
    Write-Host "║  $status $($result.Phase): $($result.Name)".PadRight(61) + "║" -ForegroundColor $color
}

Write-Host @"
╠══════════════════════════════════════════════════════════════╣
║  Summary: $successCount/$totalPhases phases passed                                  ║
║  Reports: $OutputDir
╚══════════════════════════════════════════════════════════════╝
"@ -ForegroundColor $(if ($successCount -eq $totalPhases) { "Green" } else { "Yellow" })

Write-Host "`nSummary Report: $summaryFile" -ForegroundColor Cyan

# Return results
return @{
    Success = ($successCount -eq $totalPhases)
    Results = $allResults
    SummaryFile = $summaryFile
    OutputDir = $OutputDir
}
